### ISSUE TITLE
Перевод быстрых сообщений и частичный перевод гаджетов

### ISSUE THREAD

**Issue by Stinper** [EmpireLC/localization#10]
LOBBY_SETTINGS_BLOOD_LORE:
- '§7Let you enable or disable'
- '§7blood while gaming'
LOBBY_SETTINGS_FLY_NAME: 'Fly'
LOBBY_SETTINGS_FLY_LORE:
- '§7Let you enable or disable
- '§7fly in a main lobby'
- '§7And in a game waiting lobby'
LOBBY_SETTINGS_HIDER_NAME: 'Hide players'
LOBBY_SETTINGS_HIDER_LORE:
- '§7Let you enable or disable'
- '§7hide the players in a lobby'
LOBBY_SETTINGS_CHAT_NAME: 'Chat'
LOBBY_SETTINGS_CHAT_LORE:
- '§7Let you enable or disable'
- '§7Opportunity write or read chat'
LOBBY_SETTINGS_MUSIC_NAME: 'Music'
LOBBY_SETTINGS_MUSIC_LORE:
- '§7Let you enable or disable'
- '§7Music in a game waiting lobby'
- '§7before the game begining'
LOBBY_SETTINGS_BOARD_NAME: 'Scoreboard'
LOBBY_SETTINGS_BOARD_LORE:
- '§7Let you enable or disable'
- '§7Display the scoreboards'
- '§7In the every lobby'
LOBBY_SETTINGS_HOLOCHAT_NAME: 'Чат голограмма'
LOBBY_SETTINGS_HOLOCHAT_LORE:
- '§7Позволяет включить или выключить'
- '§7отображение голограммы над игроком,'
- '§7которая содержит то, что он написал'
LOBBY_SETTINGS_PRIVATE_MESSAGE_NAME: 'Private messages'
LOBBY_SETTINGS_PRIVATE_MESSAGE_LORE:
- '§7Let you enable or disable'
- '§7private messages'
- ''
- '§cATTENTION! §7Your friend can'
- '§7wtire to you if you disable'
- '§7private messages'
LOBBY_SETTINGS_FRIENDS_REQUEST_NAME: 'Friends requests'
LOBBY_SETTINGS_FRIENDS_REQUEST_LORE:
- '§7Let you enable or disable'
- '§7Opportunity send the'
- '§7friends requests to you'
LOBBY_SETTINGS_PARTY_REQUEST_NAME: 'Party requests'
LOBBY_SETTINGS_PARTY_REQUEST_LORE:
- '§7Let you enable or disable'
- '§7opportunity send you party requests'
- ''
- '§cATTENTION! §7Your friend still can'
- '§7send you the party request'
LOBBY_SETTINGS_GUILD_REQUEST_NAME: 'Guilds requests'
LOBBY_SETTINGS_GUILD_REQUEST_LORE:
- '§7Let you enable or disable'
- '§7opportunity send you guilds requests'
LOBBY_SETTINGS_DONATE_CHAT_NAME: 'Donate chat'
LOBBY_SETTINGS_DONATE_CHAT_LORE:
- '§7Let you enable or disable'
- '§7Donate chat §f/dc'
- '§7through the whole server'
LOBBY_SERVER_NOT_FOUND_NAME: '§cThere are no running servers'
LOBBY_SERVER_NOT_FOUND_LORE:
- '§7At the moments'
- '§7there are no servers'
- '§7where game has started'
LOBBY_SERVER_SPECTATE_LORE:
- '§7Map: §b%s'
- '§7Online: §a%s§7/§c%s'
- ''
- '§e§e▸ Click to spectate for the game'
ISLAND_FLAG_ENTITY_GRIF_NAME: 'Mob griefing'
ISLAND_FLAG_ENTITY_GRIF_LORE:
- ''
- '§7If annoying mobs'
- '§7constantly steal your blocks'
- '§7this flag will solve'
- '§7all your problems'
AVAILABLE_SERVER_NOT_FOUND: '§6Server §8| §fCould not find the suitable server'
LOBBY_SPECTATE_GUI_NAME: 'Game spectating'
LOBBY_CHANNEL_GUI_NAME: 'Map choosing %s'
LOBBY_CHANNEL_MAP_LORE:
- '§7Total arenas: §c%s'
- '§7Free arenas: §c%s'
LOBBY_CHANNEL_GUI_NO_SERVERS:
- '§cError, could not find'
- '§csuitable servers'
LOBBY_CHANNEL_BEST_SERVER_NAME: '§eThe best server'
LOBBY_CHANNEL_BEST_SERVER_LORE:
- '§7Choos the most optimal'
- '§7server for gaming'
- ''
- '§e§e▸ Click to find the server'
LOBBY_DISABLED_MESSAGE_TO_CHAT: '§cError, you cannot write to chat because you disabled it.'
FAST_MESSAGE_GO: 'Go'
FAST_MESSAGE_SLEEP: 'Sleeping'
FAST_MESSAGE_CAPITULATE: 'Capitulating'
FAST_MESSAGE_MAJOR: 'Major'
FAST_MESSAGE_ENRAGES: 'Enraging'
FAST_MESSAGE_HELLO: 'Hello'
FAST_MESSAGE_GOODBYE: 'Good bye'
FAST_MESSAGE_HUGGING: 'Hugging'
FAST_MESSAGE_SAD: 'Sad'
FAST_MESSAGE_JEEZ: 'Ohoo'
FAST_MESSAGE_WHY: 'Whuut?'
FAST_MESSAGE_ACCESSIBLY: 'Accessibly'
FAST_MESSAGE_DONT_STUPID: 'Do not stupid'
FAST_MESSAGE_NICELY: 'Nicely'
FAST_MESSAGE_OFFENSIVELY: 'Offensively'
FAST_MESSAGE_WTF: 'WTF???'
FAST_MESSAGE_KILLED: 'Killed'
FAST_MESSAGE_DANCING: 'Dancing'
FAST_MESSAGE_XZ: 'IDK'
FAST_MESSAGE_EATING: 'Eating'
FAST_MESSAGE_GO_AWAY: 'Go away'
FAST_MESSAGE_MUSIC: 'Listen to music'
FAST_MESSAGE_FUCK: 'FUCK YOU'
FAST_MESSAGE_WOW: 'Wow, cool'
FAST_MESSAGE_LOVE: 'Love'
FAST_MESSAGE_LAGS: 'Lags'
FAST_MESSAGE_EASY: 'EASY'
FAST_MESSAGE_GIVE_RESOURCES: 'Give me resources'
FAST_MESSAGE_LORE1: '§7Message: §a%s'
FAST_MESSAGE_LORE2:
- ''
- '§e▸ Click to send messages'
PROFILE_MAIN_ITEM_COSMETIC_NAME: 'Effects shop'
PROFILE_MAIN_ITEM_COSMETIC_LORE:
- '§7Let you purchase and activate'
- '§7Any cosmetic upgrades:'
- '§fDeath rattle§7, §fEffect of the arrows flying§7,'
- '§fKilling effects§7, §fWinning effects§7 etc.'
- '§7'
- '§cATTENTION! All effects will work'
- '§con the all arenas and games'
- ''
- '§e▸ Open the upgrading menu'
DONATE_MENU_JOIN_MESSAGE_NAME: 'Entering messages'
DONATE_MENU_JOIN_MESSAGE_LORE:
- '§7Establish the custom alert of'
- '§7your server entering'
- ''
- '§7Available for §e§lGOLD §7and higher'
- ''
- '§e▸ Click to open menu'
JOIN_MESSAGE_NAME: 'Message %s'
JOIN_MESSAGE_LORE:
- '§7Establish the custom alert'
- '§7for the all players about you enter'
- ''
- '§7Alerts for the players:'
- '%s'
JOIN_MESSAGE_LORE_SELECT: '§aMessages are not chosen'
JOIN_MESSAGE_LORE_NOT_SELECT: '§e▸ Click to choose'
JOIN_MESSAGE_LORE_NOT_AVAILABLE: '§cThis message is not available for you'
LIMBO_NO_CHAT: '§6Server §8| §fSorry, but you cannot write to §achat§f. Come back to the main lobby §7/hub §for §7/lobby'
LIMBO_ITEM_NAME: 'Back to main lobby'
LIMBO_ITEM_LORE:
- '§7Use this item to'
- '§7come back to the main lobby'
GADGET_HAT_ON_PLAYER: 'Hat'
GADGET_BANNER_ON_PLAYER: 'Banner'
GADGET_EMOTE_ON_PLAYER: 'Emotion'
GADGET_CLICK_TO_USE_LORE:
- '§7Click RMB to activate gadget'
GADGET_FAVORITE_CLEAR_NAME: '§cClear favotites'
GADGET_FAVORITE_CLEAR_LORE:
- '§7Click to clean all gadgets'
- '§7from the favorites'
GADGET_FAVORITE_NAME: '§aFavorites'
GADGET_FAVORITE_LORE:
- '§7Favorites menu is a menu for'
- '§7fast activating any gadgets'
- '§7that you can adjust for yourself'
- '§7'
- '§7For adding gadget to the favorites'
- '§7Click §cRMB §7to the icon of wishful gadget'
GADGET_SETTING_SHOW_MORPH_NAME: '§eReincarnation'
GADGET_SETTING_SHOW_MORPH_LORE:
- '§7Activate this option'
- '§7if you want to see yourself'
- '§7like a mob'
GADGET_ALREADY_HAVE: '§fYou are already have this gadget, you got §6+%s %s'
GADGET_HAT_TYPE: 'Hat'
GADGET_PETS_TYPE: 'Pet'
GADGET_COMPANION_TYPE: 'Companion'
GADGET_EFFECT_TYPE: 'Effect'
GADGET_BANNERS_TYPE: 'Banner'
GADGET_SPIRITS_TYPE: 'Spirit'
GADGET_GADGETS_TYPE: 'Mechanisms'
GADGET_MORPH_TYPE: 'Reincarnation'
GADGET_EMOTES_TYPE: 'Emotes'
GADGET_MAIN_GUI_NAME: 'Gagdets'
GADGET_SEARCH_GUI_NAME: 'Search'
GADGET_SETTINGS_GUI_NAME: 'Settings'
GADGET_SETTINGS_GUI_LORE:
- '§7Personal settings for'
- '§7customisations gadgets'
- '§7for every player'
- ''
- '§e▸ Click to open menu'
GADGET_DELETED_GUI_NAME: 'Gadgets disabling'
GADGET_DELETED_NOT_FOUND: 'No active gadgets'
GADGET_DELETED_ALL: 'Disable all gadgets'
GADGET_DELETED_GUI_LORE:
- ''
- '§7Activated gadgets list'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_INFO_NAME: '§aTotal statistics'
GADGETS_GUI_INFO_LORE1: '§7Gadgets types'
GADGETS_GUI_INFO_LORE2:
- '§7Allowed gadgets §a%s'
- '§8• %s §6%s'
GADGETS_NOT_ACTIVATED: '§cNot activated'
GADGETS_GUI_HAT_NAME: 'Hats'
GADGETS_GUI_HAT_LORE:
- ''
- '§7Here you can choose the best hats'
- '§7from the wardrobe of the LastCraft'
- '§7No, no, you will could not take'
- '§7the rabbit from the hat'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated hat:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_EFFECT_NAME: 'Effects
GADGETS_GUI_EFFECT_LORE:
- ''
- '§7Do you want to be effective in every sense'
- '§7of this word? This section is for you!'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated effect:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_BANNERS_NAME: 'Banners'
GADGETS_GUI_BANNERS_LORE:
- ''
- '§7Any flags and nice pictures'
- '§7that you can put on like a'
- '§7hat'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated banner:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_SPIRITS_NAME: 'Spirits'
GADGETS_GUI_SPIRITS_LORE:
- ''
- '§7Your truthful friend, that'
- '§7will follow you, when you are alive'
- '§7Feel yourself like a King Of Shamans'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated spirit:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_EMOTES_NAME: 'Emotes'
GADGETS_GUI_EMOTES_LORE:
- ''
- '§7Do you want to describe your feels but'
- '§7you dont have any words? They are not'
- '§7needed because you have our emotes'
- ''
- '§7Allowed §a%s/%s §6%s'
- '§7Activated emote:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_COMPANION_NAME: 'Companions'
GADGETS_GUI_COMPANION_LORE:
- ''
- '§7There have any little and nice'
- '§7creations, that will liked you'
- '§7Just dont keep them in a cages'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated companion:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_MORPH_NAME: 'Reincornations'
GADGETS_GUI_MORPH_LORE:
- ''
- '§7Experiens the fate of any creations'
- '§7on yourself! Like a cat, creeper or cat'
- '§7or a zombie. No, cat is still better'
- '§7It is nice :3'
- ''
- '§7Allowed §a%s/%s §6%s'
- '§7Ativated reincarnation:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_PETS_NAME: 'Pets'
GADGETS_GUI_PETS_LORE:
- ''
- '§7Do you want the manual pet?'
- '§7This section is for you! Only look at'
- '§7this creeper, it is so nice, ohh'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated pet:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_GUI_GADGETS_NAME: 'Mechanisms'
GADGETS_GUI_GADGETS_LORE:
- ''
- '§7Interesting items for entertaiment'
- '§7in a lobby, or for joking on a friends'
- ''
- '§7Allowed: §a%s/%s §6%s'
- '§7Activated mechanism:'
- '%s'
- ''
- '§e▸ Click to open menu'
GADGETS_HOLIDAY_DEFAULT: '§7Default'
GADGETS_HOLIDAY_HALLOWEEN: '§6Halloween'
GADGETS_HOLIDAY_SUMMER: '§eSummer'
GADGETS_HOLIDAY_NEW_YEARS: '§cNew Year'
GADGETS_HOLIDAY_AVAILABLE: '§7Allowed in a %s §7holidays'
GADGETS_CAN_AVAILABLE: 'Can get from:'
GADGETS_GIVE_MONEY: '§7Price: §6%s coins'
GADGETS_GIVE_DONATE: '§7From a %s &7rank and higher'
GADGETS_GIVE_DONATE_ONLY: '§7Free for %s'
GADGETS_GIVE_GOLD: '§7Price: §e%s §7gold'
GADGETS_GIVE_BOX: '§7Can get from a §bLucky Chest §7(%s§7)'
GADGETS_GIVE_LEVEL: '§7By getting §d%s §7level'
GADGETS_GIVE_SITE: '§7Purchase on a §blast-craft.com'
GADGETS_NO_USE: '§cThis gadget is not available for you'
GADGETS_FAVORITE_ADD: '§aClick LMB to add in a favorites'
GADGETS_FAVORITE_REMOVE: '§cClick RMB to clean from favorites'
GADGETS_ENABLE_LORE: '§e► Click to activate gadget'
GADGETS_DISABLE_LORE: '§c► Click to deactivate gadget'

**Comment by variationtime** [comment]
Желательно допиши, все ключи новые? И на гит убирает стрелки, если можешь, скинь перевод мне файлом в вк - https://vk.com/danilashchebet

**Comment by variationtime** [comment]
актуально?
